export const countryActionsType = {
  GET_COUNTRY_REQUEST: 'GET_COUNTRY_REQUEST',
  SET_COUNTRY_REQUEST: 'SET_COUNTRY_REQUEST',
  SET_COUNTRY_DETAIL: 'SET_COUNTRY_DETAIL',
  GET_WEATHER_DETAIL: 'GET_WEATHER_DETAIL',
  SET_WEATHER_DETAIL: 'SET_WEATHER_DETAIL',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
};
